# Generated by Django 4.2.5 on 2023-09-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
