# Generated by Django 4.2.5 on 2023-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_courseno_remove_course_id_and_more'),
        ('users', '0004_student_quotaaccepttest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='quotaAccepttest',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quotaAccept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quotaRequest',
        ),
        migrations.AddField(
            model_name='student',
            name='quotaAccept',
            field=models.ManyToManyField(related_name='quotaAccept', to='course.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='quotaRequest',
            field=models.ManyToManyField(related_name='quotaRequest', to='course.course'),
        ),
    ]
