# Generated by Django 4.2.5 on 2023-09-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_courseno_remove_course_id_and_more'),
        ('users', '0005_remove_student_quotaaccepttest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='quotaRequest',
            new_name='quotaRequested',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quotaAccept',
        ),
        migrations.AddField(
            model_name='student',
            name='quotaAccepted',
            field=models.ManyToManyField(related_name='quotaAccepted', to='course.course'),
        ),
    ]
