# Generated by Django 4.2.5 on 2023-09-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_quotarequest_student_quotarequested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='quotaAccepted',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quotaRequested',
        ),
    ]
