# Generated by Django 4.2.5 on 2023-09-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_id'),
        ('users', '0008_student_user'),
    ]

    operations = [
    ]
