# Generated by Django 4.2.5 on 2023-09-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0008_alter_student_id_0008_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
