# Generated by Django 4.2.5 on 2023-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='valid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
