# Generated by Django 4.2.5 on 2023-09-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_student_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='valid',
        ),
        migrations.AddField(
            model_name='student',
            name='coursenumber',
            field=models.IntegerField(default=0),
        ),
    ]
