# Generated by Django 4.2.5 on 2023-09-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_student_valid_student_coursenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='coursenumber',
        ),
    ]
