# Generated by Django 4.2.5 on 2023-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_student_coursenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
