# Generated by Django 4.2.5 on 2023-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_enrollment_student_enrolled_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Enrolled_Course',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
