# Generated by Django 4.2.5 on 2023-09-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNo', models.CharField(max_length=10)),
                ('courseName', models.CharField(max_length=64)),
                ('courseSemester', models.IntegerField()),
                ('courseYear', models.IntegerField()),
                ('courseChair', models.IntegerField()),
                ('courseQuotaStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
