# Generated by Django 4.2.5 on 2023-09-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_courseno_remove_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursecredit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
