# Generated by Django 4.2.5 on 2023-09-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_student_quotaaccepted_and_more'),
        ('course', '0004_course_coursecredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='users.student')),
            ],
        ),
    ]
