# Generated by Django 4.2.5 on 2023-09-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_enrollment_courseid_alter_enrollment_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='studentID',
            new_name='student',
        ),
    ]
