# Generated by Django 4.2.5 on 2023-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_enroll_stu_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='courseName',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
