# Generated by Django 4.2.5 on 2023-09-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_enrollment_course_alter_enrollment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='isQuotaAvaliable',
            new_name='allowQuota_whenAvailable',
        ),
        migrations.AddField(
            model_name='course',
            name='availableChairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='quotaRecieveing_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseChair',
            field=models.IntegerField(default=0),
        ),
    ]
