# Generated by Django 4.2.5 on 2023-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_isquotaavaliable_course_allowquota_whenavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quotaRecieveing_Status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
