# Generated by Django 4.2.5 on 2023-09-24 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_student_quotaaccepted_and_more'),
        ('course', '0009_alter_course_quotarecieveing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('requestID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
