# Generated by Django 4.2.5 on 2023-09-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_quotarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotarequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
