# Generated by Django 4.2.5 on 2023-09-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_delete_enroll'),
        ('course', '0011_quotarequest_approved'),
    ]

    operations = [
    ]
