# Generated by Django 4.2.5 on 2023-09-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_merge_0008_delete_enroll_0011_quotarequest_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coursecredit',
        ),
    ]
