# Generated by Django 4.2.5 on 2023-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_course_coursecredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='availableChairs',
            field=models.IntegerField(editable=False),
        ),
    ]
