# Generated by Django 4.2.5 on 2023-09-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_quotaall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotaall',
            name='quotaRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.quotarequest'),
        ),
    ]
