# Generated by Django 4.2.5 on 2023-09-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_quotaall_quotarequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotaAll',
        ),
    ]
