# Generated by Django 4.2.5 on 2023-09-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_alter_course_availablechairs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quotaRecieveing_Status',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
