# Generated by Django 4.2.5 on 2023-09-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_student_user'),
        ('course', '0025_alter_course_quotarecieveing_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Quota_accepeted',
        ),
    ]
