# Generated by Django 4.2.5 on 2023-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_rename_enrollment_quota_accepeted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotarequest',
            name='requestID',
            field=models.UUIDField(default=int, primary_key=True, serialize=False),
        ),
    ]
