# Generated by Django 4.2.5 on 2023-09-24 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_alter_quotarequest_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotarequest',
            name='requestID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
