# Generated by Django 4.2.5 on 2023-09-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_alter_course_names_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='names_student',
        ),
    ]
