# Generated by Django 4.2.5 on 2023-09-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_student_coursenumber'),
        ('course', '0031_remove_course_names_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota_rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_enrollments', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_enrollments', to='users.student')),
            ],
        ),
    ]
