# Generated by Django 4.2.5 on 2023-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_quota_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_info',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
