# Generated by Django 4.2.5 on 2023-09-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_alter_course_student_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_info',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
