# Generated by Django 4.2.5 on 2023-09-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_alter_course_student_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota_accepeted',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_course', to='course.course'),
        ),
    ]
