# Generated by Django 4.2.5 on 2023-10-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_alter_quota_accepeted_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='quota_accepeted',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.course'),
        ),
    ]
