# Generated by Django 4.2.5 on 2023-10-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_alter_course_student_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='withdraw_status',
            field=models.BooleanField(default=False),
        ),
    ]
